import {StyleSheet} from 'react-native';
import type {Theme} from '../contexts/ThemeContext';
import {BRAND_ACCENT, cardShadow} from './appScreenTheme';
export function createWorkoutScreenStyles(
  theme: Theme,
  isDark: boolean,
) {
  const c = theme.colors;
  const greenPanelBg = isDark ? 'rgba(46, 125, 50, 0.24)' : '#E8F5E8';
  const routineDiffBg = isDark ? 'rgba(78, 205, 196, 0.16)' : '#E8F5F5';
  const exerciseDiffBg = isDark ? 'rgba(255, 107, 107, 0.2)' : '#FFE8E8';
  const personalBadgeBg = isDark ? 'rgba(150, 206, 180, 0.2)' : '#F0F8F0';

  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: c.card,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
  },
  backButton: {
    padding: 10,
    minWidth: 48,
    minHeight: 44,
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: 16,
    color: BRAND_ACCENT,
    fontWeight: '600',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: c.text,
  },
  headerRight: {
    minWidth: 48,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  section: {
    backgroundColor: c.card,
    borderWidth: 1,
    borderColor: c.border,
    margin: 10,
    borderRadius: 12,
    padding: 20,
    ...cardShadow(c),
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 15,
  },
  plannerPersistHint: {
    fontSize: 12,
    color: c.textSecondary,
    marginTop: -8,
    marginBottom: 12,
    lineHeight: 18,
  },
  muscleGroupsContainer: {
    paddingHorizontal: 5,
  },
  muscleGroupCard: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 5,
    alignItems: 'center',
    minWidth: 100,
    borderLeftWidth: 4,
    borderLeftColor: BRAND_ACCENT,
  },
  muscleGroupCardActive: {
    backgroundColor: greenPanelBg,
    borderLeftColor: '#2E7D32',
    borderLeftWidth: 6,
  },
  muscleGroupIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  muscleGroupName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: c.text,
    textAlign: 'center',
  },
  muscleGroupNameActive: {
    color: '#2E7D32',
  },
  muscleGroupDescription: {
    fontSize: 10,
    color: c.textSecondary,
    textAlign: 'center',
    marginTop: 4,
  },
  muscleGroupDescriptionActive: {
    color: '#4CAF50',
  },
  routineCard: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: BRAND_ACCENT,
  },
  routineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  routineName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
  },
  routineDifficulty: {
    fontSize: 12,
    color: BRAND_ACCENT,
    backgroundColor: routineDiffBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  routineDescription: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 10,
  },
  routineStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  routineStat: {
    fontSize: 12,
    color: c.textSecondary,
  },
  exerciseCard: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B6B',
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
  },
  exerciseDifficulty: {
    fontSize: 12,
    color: '#FF6B6B',
    backgroundColor: exerciseDiffBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  exerciseDescription: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 10,
  },
  exerciseVideoWrap: {
    width: '100%',
    height: 160,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
    backgroundColor: c.background,
  },
  exerciseVideoPreview: {
    width: '100%',
    height: '100%',
  },
  exerciseVideoOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  exerciseVideoPlayLabel: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  exerciseStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exerciseStat: {
    fontSize: 12,
    color: c.textSecondary,
  },
  // Workout in progress styles
  workoutContainer: {
    flex: 1,
    backgroundColor: c.background,
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: c.card,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
  },
  workoutTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: c.text,
  },
  currentExerciseCard: {
    backgroundColor: c.card,
    borderWidth: 1,
    borderColor: c.border,
    margin: 20,
    borderRadius: 12,
    padding: 20,
    ...cardShadow(c),
  },
  exerciseTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 8,
  },
  exerciseSubtitle: {
    fontSize: 16,
    color: c.textSecondary,
    marginBottom: 20,
  },
  progressSection: {
    marginBottom: 20,
  },
  progressTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 15,
  },
  progressStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  progressItem: {
    alignItems: 'center',
  },
  progressValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: BRAND_ACCENT,
  },
  progressLabel: {
    fontSize: 12,
    color: c.textSecondary,
    marginTop: 4,
  },
  instructionsSection: {
    marginBottom: 20,
  },
  instructionsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 10,
  },
  instructionText: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 8,
    lineHeight: 20,
  },
  workoutButtons: {
    alignItems: 'center',
  },
  completeSetButton: {
    backgroundColor: BRAND_ACCENT,
    borderRadius: 12,
    padding: 15,
    minWidth: 200,
    alignItems: 'center',
    shadowColor: c.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  completeSetButtonText: {
    color: c.buttonText,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Filter styles
  filterContainer: {
    marginBottom: 15,
  },
  filterGroup: {
    marginBottom: 15,
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 8,
  },
  filterButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterButton: {
    backgroundColor: c.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.border,
  },
  filterButtonActive: {
    backgroundColor: BRAND_ACCENT,
    borderColor: BRAND_ACCENT,
  },
  filterButtonText: {
    fontSize: 12,
    color: c.textSecondary,
  },
  filterButtonTextActive: {
    color: c.buttonText,
    fontWeight: 'bold',
  },
  bodyMapCard: {
    backgroundColor: c.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    padding: 12,
    marginBottom: 10,
  },
  bodyMapHint: {
    fontSize: 12,
    color: c.textSecondary,
    marginBottom: 10,
    textAlign: 'center',
  },
  bodyMapRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
    gap: 8,
  },
  bodyFigure: {
    height: 300,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: isDark ? '#16181d' : '#f3f5f8',
    marginBottom: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  bodyFigureHead: {
    position: 'absolute',
    top: '4%',
    left: '42%',
    width: '16%',
    height: 36,
    borderRadius: 18,
    backgroundColor: isDark ? '#20252d' : '#dfe5ee',
    borderWidth: 1,
    borderColor: c.border,
  },
  bodyFigureTorso: {
    position: 'absolute',
    top: '18%',
    left: '30%',
    width: '40%',
    height: 150,
    borderRadius: 24,
    backgroundColor: isDark ? '#1b2028' : '#e7ecf3',
    borderWidth: 1,
    borderColor: c.border,
  },
  bodyFigureLegLeft: {
    position: 'absolute',
    top: '63%',
    left: '34%',
    width: '14%',
    height: 90,
    borderRadius: 18,
    backgroundColor: isDark ? '#1b2028' : '#e7ecf3',
    borderWidth: 1,
    borderColor: c.border,
  },
  bodyFigureLegRight: {
    position: 'absolute',
    top: '63%',
    left: '52%',
    width: '14%',
    height: 90,
    borderRadius: 18,
    backgroundColor: isDark ? '#1b2028' : '#e7ecf3',
    borderWidth: 1,
    borderColor: c.border,
  },
  bodyMapZone: {
    backgroundColor: c.card,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    minWidth: 88,
    alignItems: 'center',
  },
  bodyMapZoneAbsolute: {
    position: 'absolute',
    backgroundColor: isDark ? 'rgba(48, 55, 67, 0.88)' : 'rgba(240, 245, 252, 0.9)',
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  bodyMapZoneActive: {
    backgroundColor: BRAND_ACCENT,
    borderColor: BRAND_ACCENT,
  },
  bodyMapZoneText: {
    fontSize: 12,
    color: c.text,
    fontWeight: '600',
  },
  bodyMapZoneTextActive: {
    color: c.buttonText,
  },
  bodyMapSelectedRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  bodyMapSelectedText: {
    color: c.text,
    fontSize: 13,
    fontWeight: '600',
  },

  // Personal routines styles
  createRoutineButton: {
    backgroundColor: '#96CEB4',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginBottom: 15,
  },
  createRoutineButtonText: {
    color: c.buttonText,
    fontSize: 16,
    fontWeight: 'bold',
  },
  presetToggleButton: {
    backgroundColor: c.card,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BRAND_ACCENT,
    marginBottom: 12,
  },
  presetToggleButtonText: {
    color: BRAND_ACCENT,
    fontSize: 14,
    fontWeight: '700',
  },
  createRoutineForm: {
    backgroundColor: c.card,
    borderRadius: 12,
    padding: 20,
    shadowColor: c.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 15,
    textAlign: 'center',
  },
  formSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 10,
    marginTop: 15,
  },
  formHint: {
    fontSize: 13,
    color: c.textSecondary,
    marginBottom: 10,
    lineHeight: 18,
  },
  routineNameInput: {
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 10,
  },
  exerciseSelectionItem: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: c.border,
  },
  exerciseSelected: {
    backgroundColor: BRAND_ACCENT,
    borderColor: BRAND_ACCENT,
  },
  exerciseSelectionText: {
    fontSize: 14,
    color: c.text,
  },
  exerciseSelectedText: {
    color: c.buttonText,
    fontWeight: 'bold',
  },
  saveRoutineButton: {
    backgroundColor: BRAND_ACCENT,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 15,
  },
  saveRoutineButtonText: {
    color: c.buttonText,
    fontSize: 16,
    fontWeight: 'bold',
  },
  routineContent: {
    flex: 1,
  },
  routineHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  personalBadge: {
    fontSize: 12,
    color: '#96CEB4',
    fontWeight: 'bold',
    backgroundColor: personalBadgeBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  deleteRoutineButton: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteRoutineText: {
    fontSize: 18,
  },

  // Timer styles
  timerSection: {
    marginBottom: 20,
    alignItems: 'center',
  },
  timerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 10,
    textAlign: 'center',
  },
  timerDisplay: {
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    minWidth: 120,
    alignItems: 'center',
  },
  timerText: {
    fontSize: 32,
    fontWeight: 'bold',
  },
  stopTimerButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 8,
    padding: 10,
    paddingHorizontal: 20,
  },
  stopTimerButtonText: {
    color: c.buttonText,
    fontSize: 14,
    fontWeight: 'bold',
  },
  quickTimerSection: {
    marginBottom: 20,
    alignItems: 'center',
  },
  quickTimerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 10,
  },
  quickTimerButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  quickTimerButton: {
    backgroundColor: BRAND_ACCENT,
    borderRadius: 8,
    padding: 12,
    paddingHorizontal: 16,
  },
  quickTimerButtonText: {
    color: c.buttonText,
    fontSize: 14,
    fontWeight: 'bold',
  },

  // Progress tracking styles
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statCard: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 3,
    borderWidth: 1,
    borderColor: c.border,
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: BRAND_ACCENT,
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 12,
    color: c.textSecondary,
    textAlign: 'center',
  },
  progressCirclesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 10,
  },
  weeklyGoalInfo: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 12,
    marginTop: 15,
    alignItems: 'center',
  },
  weeklyGoalText: {
    fontSize: 12,
    color: c.textSecondary,
    fontWeight: '500',
  },
  calendarGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingVertical: 10,
  },
  calendarLegend: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: c.border,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 5,
  },
  legendText: {
    fontSize: 11,
    color: c.textSecondary,
  },
  emptyState: {
    alignItems: 'center',
    padding: 30,
  },
  emptyStateEmoji: {
    fontSize: 48,
    marginBottom: 10,
  },
  emptyStateText: {
    fontSize: 14,
    color: c.textSecondary,
    textAlign: 'center',
  },
  // Quick stats styles
  quickStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
    paddingVertical: 15,
    backgroundColor: c.surface,
    borderRadius: 12,
  },
  quickStat: {
    alignItems: 'center',
  },
  quickStatValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: BRAND_ACCENT,
  },
  quickStatLabel: {
    fontSize: 12,
    color: c.textSecondary,
    marginTop: 4,
  },
  calendarTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 15,
    marginTop: 10,
  },
  // Modal styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: c.card,
    borderRadius: 20,
    padding: 20,
    margin: 20,
    maxHeight: '80%',
    width: '90%',
    shadowColor: c.shadow,
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: c.text,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: c.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: c.textSecondary,
    fontWeight: 'bold',
  },
  // Workout details styles
  workoutDetails: {
    alignItems: 'center',
  },
  workoutDetailTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 8,
  },
  workoutDetailDate: {
    fontSize: 16,
    color: c.textSecondary,
    marginBottom: 8,
  },
  workoutDetailType: {
    fontSize: 14,
    color: c.textMuted,
    marginBottom: 16,
  },
  workoutDetailStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  workoutDetailStat: {
    alignItems: 'center',
  },
  workoutDetailStatValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: BRAND_ACCENT,
  },
  workoutDetailStatLabel: {
    fontSize: 14,
    color: c.textSecondary,
    marginTop: 4,
  },
  workoutDetailExerciseList: {
    width: '100%',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: c.border,
  },
  workoutDetailExerciseTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: c.text,
    marginBottom: 8,
  },
  workoutDetailExerciseItem: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 6,
  },
  // Exercise details styles
  exerciseDetails: {
    maxHeight: 400,
  },
  exerciseDetailName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 8,
  },
  exerciseDetailDescription: {
    fontSize: 16,
    color: c.textSecondary,
    marginBottom: 20,
    lineHeight: 24,
  },
  exerciseDetailVideoWrap: {
    width: '100%',
    height: 220,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 16,
    backgroundColor: c.surface,
  },
  exerciseDetailVideo: {
    width: '100%',
    height: '100%',
  },
  exerciseDetailImage: {
    width: '100%',
    height: 200,
    marginBottom: 16,
    borderRadius: 8,
    backgroundColor: c.surface,
  },
  exerciseDetailInfo: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  exerciseDetailInfoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  exerciseDetailInfoLabel: {
    fontSize: 14,
    color: c.textSecondary,
    fontWeight: '500',
  },
  exerciseDetailInfoValue: {
    fontSize: 14,
    color: c.text,
    fontWeight: '600',
  },
  exerciseInstructions: {
    backgroundColor: c.surface,
    borderRadius: 12,
    padding: 15,
  },
  exerciseInstructionsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
    marginBottom: 10,
  },
  exerciseInstruction: {
    fontSize: 14,
    color: c.text,
    lineHeight: 20,
    marginBottom: 8,
  },
  addToRoutineActions: {
    marginTop: 16,
    marginBottom: 8,
    gap: 10,
  },
  addToRoutineButton: {
    backgroundColor: '#96CEB4',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  addToRoutineButtonText: {
    color: c.buttonText,
    fontSize: 16,
    fontWeight: 'bold',
  },
  createRoutineFromExerciseButton: {
    backgroundColor: c.card,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BRAND_ACCENT,
  },
  createRoutineFromExerciseButtonText: {
    color: BRAND_ACCENT,
    fontSize: 16,
    fontWeight: 'bold',
  },
  pickRoutineList: {
    maxHeight: 320,
  },
  pickRoutineItem: {
    padding: 14,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
  },
  pickRoutineItemName: {
    fontSize: 16,
    fontWeight: '700',
    color: c.text,
    marginBottom: 4,
  },
  pickRoutineItemMeta: {
    fontSize: 13,
    color: c.textSecondary,
    lineHeight: 18,
  },
  pickRoutineEmpty: {
    paddingVertical: 12,
    gap: 12,
  },
  pickRoutineEmptyText: {
    fontSize: 14,
    color: c.textSecondary,
    textAlign: 'center',
  },
  historyCard: {
    backgroundColor: c.card,
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: c.border,
    shadowColor: c.shadow,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  historyRoutineName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: c.text,
  },
  historyDate: {
    fontSize: 12,
    color: c.textSecondary,
  },
  historyStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  historyStat: {
    fontSize: 14,
    color: BRAND_ACCENT,
    fontWeight: '600',
  },

  // Clear filter button styles
  clearFilterButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#FF6B6B',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 10,
  },
  clearFilterText: {
    color: c.buttonText,
    fontSize: 12,
    fontWeight: 'bold',
  },

  // Workout planner styles
  plannerToggleButton: {
    backgroundColor: BRAND_ACCENT,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  plannerToggleText: {
    color: c.buttonText,
    fontSize: 16,
    fontWeight: 'bold',
  },
  plannerDayCard: {
    backgroundColor: c.card,
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: c.border,
    shadowColor: c.shadow,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  plannerDayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  plannerDayName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: c.text,
  },
  removePlanButton: {
    padding: 5,
  },
  removePlanText: {
    fontSize: 16,
  },
  plannedRoutine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: greenPanelBg,
    borderRadius: 8,
    padding: 12,
  },
  plannedRoutineName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2E7D32',
  },
  startPlannedButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  startPlannedText: {
    color: c.buttonText,
    fontSize: 14,
    fontWeight: 'bold',
  },
  routineSelector: {
    marginTop: 5,
  },
  selectorLabel: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 8,
  },
  routineButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  routineSelectButton: {
    backgroundColor: c.surface,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: c.border,
  },
  routineSelectText: {
    fontSize: 12,
    color: c.text,
    fontWeight: '600',
  },
  });
}
