import {StyleSheet} from 'react-native';
import type {Theme} from '../../../../src/contexts/ThemeContext';

const ACCENT = '#4ECDC4';

/**
 * Themed styles for Community (feed, challenges, leaderboard, badges, modals).
 */
export function createCommunityStyles(theme: Theme, isDark: boolean) {
  const c = theme.colors;
  return StyleSheet.create({
    container: {flex: 1, backgroundColor: c.surface},
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: c.card,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    backButton: {
      padding: 10,
      minWidth: 48,
      minHeight: 48,
      justifyContent: 'center',
    },
    backButtonText: {fontSize: 16, color: ACCENT, fontWeight: '600'},
    title: {fontSize: 24, fontWeight: 'bold', color: c.text},
    notificationButton: {
      padding: 10,
      minWidth: 48,
      minHeight: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    notificationIcon: {fontSize: 20},
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: c.card,
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    tabButton: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      borderRadius: 8,
      marginHorizontal: 5,
    },
    tabButtonActive: {backgroundColor: ACCENT},
    tabIcon: {fontSize: 20, marginBottom: 4},
    tabLabel: {fontSize: 12, color: c.textSecondary, fontWeight: '600'},
    tabLabelActive: {color: 'white'},
    content: {flex: 1},
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: c.text,
      marginBottom: 15,
    },
    feedHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: 20,
      marginTop: 20,
    },
    newPostBtn: {
      backgroundColor: ACCENT,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
    },
    newPostBtnText: {color: 'white', fontWeight: '700', fontSize: 14},
    feedContainer: {paddingHorizontal: 0, paddingBottom: 24},
    feedItem: {
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 15,
      marginHorizontal: 20,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    feedHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    userInfo: {flexDirection: 'row', alignItems: 'center'},
    userAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: ACCENT,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    userAvatarText: {color: 'white', fontSize: 18, fontWeight: 'bold'},
    userName: {fontSize: 16, fontWeight: 'bold', color: c.text},
    feedTime: {fontSize: 12, color: c.textSecondary, marginTop: 2},
    moreButton: {padding: 5},
    moreButtonText: {fontSize: 18, color: c.textSecondary},
    feedContent: {
      fontSize: 16,
      color: c.text,
      lineHeight: 22,
      marginBottom: 10,
    },
    feedVideoWrap: {
      width: '100%',
      borderRadius: 10,
      overflow: 'hidden',
      marginBottom: 12,
      backgroundColor: c.background,
    },
    feedVideo: {
      width: '100%',
      aspectRatio: 16 / 9,
      backgroundColor: c.background,
    },
    feedImagesRow: {marginBottom: 12},
    feedImage: {
      width: 220,
      height: 160,
      borderRadius: 10,
      marginRight: 10,
      backgroundColor: isDark ? '#2C2C2E' : '#ECEFF1',
    },
    composeModalScroll: {flexGrow: 1, justifyContent: 'center', paddingVertical: 8},
    composeSubtitle: {
      fontSize: 13,
      color: c.textSecondary,
      lineHeight: 18,
      marginBottom: 14,
    },
    addPhotoBtn: {
      alignSelf: 'flex-start',
      backgroundColor: isDark ? 'rgba(78, 205, 196, 0.15)' : '#E8F8F7',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: ACCENT,
    },
    addPhotoBtnText: {color: isDark ? '#7fe8dd' : '#1a8a84', fontWeight: '700', fontSize: 14},
    composeVideoRow: {marginBottom: 6},
    composeVideoPill: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
      borderRadius: 8,
      backgroundColor: isDark ? 'rgba(100, 150, 200, 0.2)' : '#E8F4FD',
      borderWidth: 1,
      borderColor: isDark ? c.border : '#B3D9F2',
    },
    composeVideoPillText: {flex: 1, fontSize: 13, color: c.text, marginRight: 8},
    composeVideoRemoveText: {color: c.error, fontWeight: '700', fontSize: 14},
    composeThumbRow: {marginBottom: 12},
    composeThumbWrap: {marginRight: 10},
    composeThumb: {
      width: 72,
      height: 72,
      borderRadius: 8,
      backgroundColor: isDark ? '#2C2C2E' : '#ECEFF1',
    },
    composeThumbRemove: {
      position: 'absolute',
      top: -6,
      right: -6,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.text,
      justifyContent: 'center',
      alignItems: 'center',
    },
    composeThumbRemoveText: {color: c.card, fontSize: 16, lineHeight: 18, fontWeight: '700'},
    composeRoadmapHint: {
      fontSize: 12,
      color: c.textMuted,
      lineHeight: 17,
      marginBottom: 8,
    },
    composeAttachedChallenge: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: 10,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: ACCENT,
      backgroundColor: isDark ? 'rgba(78, 205, 196, 0.12)' : '#E8F8F7',
    },
    composeAttachedChallengeTextCol: {
      flex: 1,
      paddingRight: 8,
    },
    composeAttachedLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: ACCENT,
      letterSpacing: 0.6,
      marginBottom: 4,
    },
    composeAttachedTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: c.text,
      paddingRight: 8,
    },
    composeAttachedReward: {
      fontSize: 13,
      color: c.textSecondary,
      marginTop: 4,
    },
    composeAttachedRemove: {
      fontSize: 14,
      fontWeight: '700',
      color: c.error,
    },
    feedSharedChallenge: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: ACCENT,
      padding: 12,
      marginBottom: 12,
      backgroundColor: isDark ? 'rgba(78, 205, 196, 0.12)' : '#E8F8F7',
    },
    feedSharedChallengeLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: ACCENT,
      letterSpacing: 0.6,
      marginBottom: 6,
    },
    feedSharedChallengeTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: c.text,
    },
    feedSharedChallengeReward: {
      fontSize: 13,
      color: c.textSecondary,
      marginTop: 6,
    },
    feedActions: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      borderTopWidth: 1,
      borderTopColor: c.border,
      paddingTop: 12,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    actionIcon: {fontSize: 16, marginRight: 6},
    actionText: {fontSize: 14, color: c.textSecondary, fontWeight: '500'},
    challengesContainer: {paddingHorizontal: 20},
    challengeCard: {
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 20,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    challengeCardFocused: {
      borderColor: ACCENT,
      shadowOpacity: 0.22,
      elevation: 6,
    },
    challengeHeader: {
      marginBottom: 10,
    },
    challengeTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: c.text,
    },
    challengeReward: {
      fontSize: 14,
      color: c.error,
      fontWeight: '600',
      marginTop: 6,
    },
    challengeDescription: {
      fontSize: 14,
      color: c.textSecondary,
      marginBottom: 15,
      lineHeight: 20,
    },
    challengeMeta: {
      fontSize: 12,
      color: c.textMuted,
      marginBottom: 10,
      lineHeight: 18,
    },
    challengeStats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    challengeParticipants: {fontSize: 14, color: ACCENT, fontWeight: '600'},
    challengeProgress: {fontSize: 14, color: c.warning, fontWeight: '600'},
    joinChallengeButton: {
      backgroundColor: ACCENT,
      borderRadius: 8,
      paddingVertical: 12,
      alignItems: 'center',
    },
    joinChallengeText: {color: 'white', fontSize: 16, fontWeight: 'bold'},
    leaderboardContainer: {paddingHorizontal: 20},
    leaderboardItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 15,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    rankContainer: {width: 50, alignItems: 'center', marginRight: 15},
    rankNumber: {fontSize: 20, fontWeight: 'bold', color: c.text},
    rankMedal: {fontSize: 16, marginTop: 2},
    userStats: {flex: 1},
    userDetails: {fontSize: 12, color: c.textSecondary, marginTop: 2},
    commentsSection: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },
    commentRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 10,
      paddingHorizontal: 4,
    },
    commentUser: {fontSize: 12, fontWeight: 'bold', color: ACCENT},
    commentText: {fontSize: 14, color: c.text},
    commentTime: {fontSize: 10, color: c.textSecondary, marginTop: 2},
    deleteComment: {fontSize: 16, paddingLeft: 8},
    commentInputContainer: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },
    commentInput: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      padding: 10,
      fontSize: 14,
      minHeight: 40,
      marginBottom: 10,
      color: c.text,
      backgroundColor: c.inputBackground,
    },
    commentInputActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    cancelCommentButton: {
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: c.surface,
      marginRight: 10,
    },
    cancelCommentText: {color: c.textSecondary, fontSize: 14, fontWeight: '600'},
    postCommentButton: {
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: ACCENT,
    },
    postCommentText: {color: 'white', fontSize: 14, fontWeight: '600'},
    actionButtonActive: {
      backgroundColor: isDark ? 'rgba(255, 107, 107, 0.2)' : '#FFE5E5',
    },
    actionIconActive: {color: c.error},
    actionTextActive: {color: c.error, fontWeight: 'bold'},
    joinedChallengeButton: {
      backgroundColor: isDark ? 'rgba(46, 125, 50, 0.35)' : '#E8F5E8',
    },
    joinedChallengeText: {color: isDark ? '#A5D6A7' : '#2E7D32'},
    shareChallengeButton: {
      marginTop: 10,
      borderRadius: 8,
      paddingVertical: 11,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: ACCENT,
      backgroundColor: 'transparent',
    },
    shareChallengeButtonText: {
      color: ACCENT,
      fontWeight: '700',
      fontSize: 15,
    },
    creatorActions: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    editChallengeBtn: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      marginRight: 6,
    },
    editChallengeText: {color: c.info, fontSize: 14, fontWeight: '600'},
    deleteChallengeBtn: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      marginLeft: 6,
    },
    deleteChallengeText: {color: c.error, fontSize: 14, fontWeight: '600'},
    notificationBadge: {
      position: 'absolute',
      top: -5,
      right: -5,
      backgroundColor: c.error,
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    notificationBadgeText: {color: 'white', fontSize: 12, fontWeight: 'bold'},
    notificationsPanel: {
      backgroundColor: c.card,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      maxHeight: 300,
    },
    notificationsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    notificationsTitle: {fontSize: 18, fontWeight: 'bold', color: c.text},
    closeNotificationsText: {fontSize: 20, color: c.textSecondary, padding: 5},
    notificationItem: {
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: c.divider,
    },
    unreadNotification: {backgroundColor: isDark ? c.surface : '#F8F9F9'},
    notificationMessage: {fontSize: 14, color: c.text, marginBottom: 5},
    notificationTime: {fontSize: 12, color: c.textSecondary},
    noNotificationsText: {
      textAlign: 'center',
      padding: 20,
      color: c.textSecondary,
      fontSize: 14,
    },
    badgesContainer: {paddingHorizontal: 20},
    badgesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    badgeCard: {
      width: '47.5%',
      backgroundColor: c.surface,
      borderRadius: 12,
      padding: 15,
      marginBottom: 14,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: c.border,
      opacity: 0.6,
    },
    badgeCardEarned: {
      backgroundColor: isDark ? 'rgba(76, 175, 80, 0.2)' : '#E8F5E8',
      borderColor: c.success,
      opacity: 1,
    },
    badgeIcon: {fontSize: 32, marginBottom: 8},
    badgeName: {
      fontSize: 14,
      fontWeight: 'bold',
      color: c.textSecondary,
      textAlign: 'center',
      marginBottom: 5,
    },
    badgeNameEarned: {color: isDark ? '#A5D6A7' : '#2E7D32'},
    badgeDescription: {
      fontSize: 12,
      color: c.textSecondary,
      textAlign: 'center',
      marginBottom: 8,
    },
    badgeDescriptionEarned: {color: c.success},
    badgeEarnedDate: {fontSize: 10, color: c.success, fontWeight: '600'},
    errorText: {
      color: c.error,
      marginHorizontal: 20,
      marginBottom: 12,
      fontSize: 14,
    },
    emptyFeed: {
      color: c.textSecondary,
      marginHorizontal: 20,
      marginBottom: 16,
      fontSize: 15,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      padding: 24,
    },
    createChallengeScroll: {flexGrow: 1, justifyContent: 'center'},
    fieldLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: c.text,
      marginBottom: 6,
      marginTop: 4,
    },
    helperText: {fontSize: 13, color: c.textSecondary, marginBottom: 12, lineHeight: 18},
    metricChip: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginBottom: 8,
    },
    metricChipActive: {
      borderColor: ACCENT,
      backgroundColor: isDark ? 'rgba(78, 205, 196, 0.2)' : '#E8F8F7',
    },
    metricChipText: {fontSize: 13, color: c.text},
    metricChipTextActive: {color: isDark ? '#7fe8dd' : '#1a8a84', fontWeight: '600'},
    badgePresetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    badgePresetEmoji: {fontSize: 22},
    badgePresetMeta: {flex: 1},
    badgePresetSubLabel: {
      fontSize: 12,
      color: c.textSecondary,
      marginTop: 2,
      lineHeight: 16,
    },
    leaderboardSubtext: {
      fontSize: 13,
      color: c.textSecondary,
      marginHorizontal: 20,
      marginBottom: 12,
      lineHeight: 18,
    },
    exRow: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      padding: 10,
      marginBottom: 6,
    },
    exRowOn: {
      borderColor: ACCENT,
      backgroundColor: isDark ? 'rgba(78, 205, 196, 0.12)' : '#F0FCFB',
    },
    exRowText: {fontSize: 14, color: c.text},
    modalCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: c.text,
      marginBottom: 12,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      minHeight: 120,
      padding: 12,
      fontSize: 16,
      textAlignVertical: 'top',
      marginBottom: 16,
      color: c.text,
      backgroundColor: c.inputBackground,
    },
    modalInputCompact: {
      minHeight: 48,
      textAlignVertical: 'center',
    },
    modalActions: {flexDirection: 'row', justifyContent: 'flex-end'},
  });
}
